// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "slicer_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// slicer_int
SEXP slicer_int(SEXP x, SEXP idx);
RcppExport SEXP _slicer_slicer_int(SEXP xSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(slicer_int(x, idx));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_slicer_slicer_int", (DL_FUNC) &_slicer_slicer_int, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_slicer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
