# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

slicer_int <- function(x, idx) {
    .Call(`_slicer_slicer_int`, x, idx)
}

